### ISSUE TITLE
Bug: slot view not loading

### ISSUE THREAD

**Issue by s1na** [ethpandaops/dora#64]
I started this kurtosis configuration:

```
participants:
    - el_type: geth
      el_image: "192.168.45.152:80/dh/ethpandaops/geth:lightclient-prague-devnet-0"
      el_image: "ethpandaops/geth:lightclient-prague-devnet-0"
      cl_type: grandine
      cl_image: ethpandaops/grandine:feature-electra
      count: 3
network_params:
  electra_fork_epoch: 1
additional_services: [dora]
snooper_enabled: true
```

Slots are being proposed but when I try to open the page for a slot I get "Internal server error".

Docker logs indicate:

```
time="2024-05-13T11:37:56Z" level=error msg="error executing template" error="html/template:slot.html:212:24: no such template \"block_consolidation\"" error type="*template.Error" file=index.go function=Slot info= route=/slot/30
```
